@select('name'=>'company_id','trans'=>'accounts','list'=>$companies,'options'=>['class' =>'js-example-basic-multiple js-states form-control'])
@number('name'=>'branch_code','trans'=>'offices','options'=>[])
@text('name'=>'name','trans'=>'offices','options'=>['required' => 'required'])
@text('name'=>'abbreviation','trans'=>'offices','options'=>[])
@textarea('name'=>'address','trans'=>'offices','options'=>[])
@text('name'=>'phone','trans'=>'offices','options'=>[])
@text('name'=>'fax','trans'=>'offices','options'=>[])
@text('name'=>'email','trans'=>'offices','options'=>[])
@text('name'=>'sales_gl_code','trans'=>'offices','options'=>[])
@text('name'=>'sales_tax_code','trans'=>'offices','options'=>[])
@text('name'=>'sed_gl_code','trans'=>'offices','options'=>[])
@text('name'=>'earning_gl_code','trans'=>'offices','options'=>[])
