{{--@text('name'=>'code','trans'=>'accounts','options'=>['class'=>'input-mask-account-group form-control'])--}}
@text('name'=>'code','trans'=>'accounts','options'=>['class'=>'input-mask-product form-control','label-size'=>'4','field-size'=>'8',])
@text('name'=>'description','trans'=>'accounts','options'=>['required' => 'required'])
@select('name'=>'account_type_id','trans'=>'accounts','list'=>$account_types,'options'=>['class' =>'js-example-basic-multiple js-states form-control'])
@select('name'=>'account_group_id','trans'=>'accounts','list'=>$account_groups,'options'=>['class' =>'js-example-basic-multiple js-states form-control'])
@text('name'=>'contact_person','trans'=>'accounts','options'=>[])
@text('name'=>'phone','trans'=>'accounts','options'=>[])
@text('name'=>'fax','trans'=>'accounts','options'=>[])
@text('name'=>'email','trans'=>'accounts','options'=>[])
@text('name'=>'address_1','trans'=>'accounts','options'=>[])
@text('name'=>'address_2','trans'=>'accounts','options'=>[])
@text('name'=>'address_3','trans'=>'accounts','options'=>[])
@select('name'=>'city_id','trans'=>'accounts','list'=>$cities,'options'=>['class' =>'js-example-basic-multiple js-states form-control'])
@text('name'=>'gst_no','trans'=>'accounts','options'=>[])
@number('name'=>'ntn','trans'=>'accounts','options'=>[])
@text('name'=>'other','trans'=>'accounts','options'=>[])
@number('name'=>'bank_ac_no','trans'=>'accounts','options'=>[])
@number('name'=>'open_debit','trans'=>'accounts','options'=>[])
@number('name'=>'open_credit','trans'=>'accounts','options'=>[])
@number('name'=>'credit_days','trans'=>'accounts','options'=>[])
