@number('name'=>'code','trans'=>'companies','options'=>[])
@text('name'=>'name','trans'=>'companies','options'=>['required' => 'required'])
@text('name'=>'abbreviation','trans'=>'companies','options'=>['required' => 'required'])
@textarea('name'=>'address','trans'=>'companies','options'=>[])
@text('name'=>'phone','trans'=>'companies','options'=>[])
@text('name'=>'fax','trans'=>'companies','options'=>[])
@text('name'=>'email','trans'=>'companies','options'=>[])
@text('name'=>'sales_tax','trans'=>'companies','options'=>[])
@text('name'=>'registration_no','trans'=>'companies','options'=>[])
@number('name'=>'ntn','trans'=>'companies','options'=>[])
